small_web_app/routes/interfaces.py
from flask import Flask, jsonify, render_template, request, redirect, Blueprint
from ncclient import manager
import xml.etree.ElementTree as ET

from constants import NAMESPACE, INTERFACE_CONFIG, BIND_INTERFACE_TO_BRIDGE_CONFIG, BIND_L2_VLAN_TO_INTERFACE, BIND_L3_VLAN_TO_INTERFACE
from filter_string_provider import provide_filter_string


interface_bp = Blueprint("interfaces", __name__, url_prefix="/interfaces")


@interface_bp.route("/")
def list_interfaces():
    netconf_filter = provide_filter_string("/ipi-interface:interfaces/ipi-interface:interface")

    with manager.connect(host="192.168.10.102", username="ocnos", password="ocnos", hostkey_verify=False) as m:
        result = m.get(filter=netconf_filter)

    tree = ET.fromstring(result.xml)

    interfaces = tree.findall(".//ipi-interface:interface", namespaces=NAMESPACE)

    all_interfaces: list[dict[str, str]] = []

    for interface in interfaces:
        name = interface.find(".//ipi-interface:name", namespaces=NAMESPACE).text
        oper_status = interface.find(".//ipi-interface:state/ipi-interface:oper-status", namespaces=NAMESPACE).text
        admin_status = interface.find(".//ipi-interface:state/ipi-interface:admin-status", namespaces=NAMESPACE).text

        all_interfaces.append({
            "name": name,
            "oper-status": oper_status,
            "admin-status": admin_status
        })

    return render_template('interfaces.html', data=all_interfaces)

@interface_bp.route("/config-interface", methods=["POST"])
@interface_bp.route("/config-interface/<name>", methods=["GET"])
def configure_interface(name=None):

    if request.method == "GET":
        is_l2_vlan = False
        vlan_id = name.split(".")[-1]

        netconf_filter = provide_filter_string("/ipi-network-instance:instances/ipi-network-instance:instance")

        with manager.connect(host="192.168.10.102", username="ocnos", password="ocnos", hostkey_verify=False) as m:
            result = m.get(filter=netconf_filter)

        tree = ET.fromstring(result.xml)

        network_instances = tree.findall(".//ipi-network-instance:network-instance", namespaces=NAMESPACE)

        for instance in network_instances:
            bridge_id_val = instance.find(".//ipi-network-instance:instance-name", namespaces=NAMESPACE).text


            if bridge_id == bridge_id_val:
                vlan_identifier = instance.find(".//ipi-vlan:vlans/ipi-vlan:vlan/ipi-vlan:vlan-id", namespaces=NAMESPACE).text
                vlan_state = instance.find(".//ipi-vlan:customer-vlan/ipi-vlan:config/ipi-vlan:state", namespaces=NAMESPACE)

                if vlan_identifier == vlan_id and vlan_state is not None:
                    is_l2_vlan = True

        return render_template("configure_interface.html", name=name, isL2Vlan=is_l2_vlan)

    if request.method == "POST":
        interface_name = request.form.get("interface-name")
        interface_ip = request.form.get("interface-ip")

        switchport_mode = request.form.get("switchport-mode")
        bind_interface_name = request.form.get("parent-interface")
        bind_bridge_id = request.form.get("bridge-interface")

        is_l2_vlan = request.form.get("is-l2-vlan")
        is_switchport = request.form.get("is-switchport")

        BIND_CONFIG = BIND_INTERFACE_TO_BRIDGE_CONFIG if bind_bridge_id is not None else BIND_L2_VLAN_TO_INTERFACE if is_l2_vlan == "True" and bind_interface_name is not None else BIND_L3_VLAN_TO_INTERFACE

        config_tree = ET.fromstring(INTERFACE_CONFIG)
        bind_config_tree = ET.fromstring(BIND_CONFIG)

        new_bind_config_tree = ""

        # Interface config xml parsing

        interface_element = config_tree.find(".//ipi-interface:interface", namespaces=NAMESPACE)
        ipv4_element = config_tree.find(".//ipi-if-ip:ipv4", namespaces=NAMESPACE)

        interface_name_tag = config_tree.find(".//ipi-interface:interface/ipi-interface:name", namespaces=NAMESPACE)
        interface_config_name_tag = config_tree.find(".//ipi-interface:interface/ipi-interface:config/ipi-interface:name", namespaces=NAMESPACE)
        interface_config_tag = config_tree.find(".//ipi-interface:interface/ipi-interface:config", namespaces=NAMESPACE)
        config_ip_tag = config_tree.find(".//ipi-if-ip:ipv4/ipi-if-ip:config/ipi-if-ip:primary-ip-addr", namespaces=NAMESPACE)

        if config_ip_tag is not None: config_ip_tag.text = interface_ip
        if interface_name_tag is not None: interface_name_tag.text = interface_name
        if interface_config_name_tag is not None: interface_config_name_tag.text = interface_name

        if interface_config_tag is not None and is_switchport:
            switchport_element = ET.Element("{http://www.ipinfusion.com/yang/ocnos/ipi-interface}enable-switchport")
            interface_config_tag.append(switchport_element)

        if is_switchport and interface_element is not None and ipv4_element is not None:
            interface_element.remove(ipv4_element)

        # Bind config xml parsing
        if bind_bridge_id is not None:
            bridge_id = bind_config_tree.find(".//ipi-network-instance:network-instance/ipi-network-instance:instance-name", namespaces=NAMESPACE)
            bridge_config_id = bind_config_tree.find(".//ipi-network-instance:network-instance/ipi-network-instance:config/ipi-network-instance:instance-name", namespaces=NAMESPACE)
            bridge_port_interface_name = bind_config_tree.find(".//ipi-bridge:bridge-ports/ipi-bridge:interface/ipi-bridge:name", namespaces=NAMESPACE)
            bridge_port_config_interface_name = bind_config_tree.find(".//ipi-bridge:bridge-ports/ipi-bridge:interface/ipi-bridge:config/ipi-bridge:name", namespaces=NAMESPACE)

            bridge_id.text = bind_bridge_id
            bridge_config_id.text = bind_bridge_id
            bridge_port_interface_name.text = interface_name
            bridge_port_config_interface_name.text = interface_name

            new_bind_config_tree = ET.tostring(bind_config_tree, encoding="unicode")

        if is_l2_vlan == "True" and bind_interface_name is not None:
            bind_interface_name_tag = bind_config_tree.find(".//ipi-interface:interface/ipi-interface:name", namespaces=NAMESPACE)
            bind_interface_config_name_tag = bind_config_tree.find(".//ipi-interface:interface/ipi-interface:config/ipi-interface:name", namespaces=NAMESPACE)
            bind_interface_mode_tag = bind_config_tree.find(".//ipi-port-vlan:switched-vlans/ipi-port-vlan:switched-vlan/ipi-port-vlan:interface-mode", namespaces=NAMESPACE)
            bind_interface_mode_config_tag = bind_config_tree.find(".//ipi-port-vlan:switched-vlans/ipi-port-vlan:switched-vlan/ipi-port-vlan:config/ipi-port-vlan:interface-mode", namespaces=NAMESPACE)
            bind_interface_vlan_id_tag = bind_config_tree.find(".//ipi-port-vlan:switched-vlans/ipi-port-vlan:switched-vlan/ipi-port-vlan:vlans/ipi-port-vlan:config/ipi-port-vlan:vlan-id", namespaces=NAMESPACE)

            bind_interface_name_tag.text = bind_interface_name
            bind_interface_config_name_tag.text = bind_interface_name
            bind_interface_mode_tag.text = switchport_mode
            bind_interface_mode_config_tag.text = switchport_mode
            bind_interface_vlan_id_tag.text = interface_name.split(".")[-1]

            new_bind_config_tree = ET.tostring(bind_config_tree, encoding="unicode")

        if is_l2_vlan == "False" and bind_interface_name is not None:
            bind_l3_interface_name_tag = bind_config_tree.find(".//ipi-interface:interface/ipi-interface:name", namespaces=NAMESPACE)
            bind_l3_interface_config_name_tag = bind_config_tree.find(".//ipi-interface:interface/ipi-interface:config/ipi-interface:name", namespaces=NAMESPACE)
            bind_l3_interface_mode_tag = bind_config_tree.find(".//ipi-port-vlan:switched-vlans/ipi-port-vlan:switched-vlan/ipi-port-vlan:interface-mode", namespaces=NAMESPACE)
            bind_l3_interface_mode_config_tag = bind_config_tree.find(".//ipi-port-vlan:switched-vlans/ipi-port-vlan:switched-vlan/ipi-port-vlan:config/ipi-port-vlan:interface-mode", namespaces=NAMESPACE)
            bind_l3_interface_vlan_id_tag = bind_config_tree.find(".//ipi-port-vlan:switched-vlans/ipi-port-vlan:switched-vlan/ipi-port-vlan:allowed-vlan/ipi-port-vlan:config/ipi-port-vlan:allowed-vlan-id", namespaces=NAMESPACE)

            bind_l3_interface_name_tag.text = bind_interface_name
            bind_l3_interface_config_name_tag.text = bind_interface_name
            bind_l3_interface_mode_tag.text = switchport_mode
            bind_l3_interface_mode_config_tag.text = switchport_mode
            bind_l3_interface_vlan_id_tag.text = interface_name.split(".")[-1]

            new_bind_config_tree = ET.tostring(bind_config_tree, encoding="unicode")

        new_config_tree = ET.tostring(config_tree, encoding="unicode")

        with manager.connect(host="192.168.10.102", username="ocnos", password="ocnos", hostkey_verify=False) as m:
            if bind_bridge_id is not None and bind_bridge_id != "":
                try:
                    result = m.edit_config(target="candidate", config=new_config_tree)
                    m.commit()

                    if "<ok/>" in str(result):
                        bind_bridge_result = m.edit_config(target="candidate", config=new_bind_config_tree)
                        m.commit()

                except Exception as e:
                    print(f"Error: {e}")
                    return redirect("/vlans/create-vlan")

            if bind_bridge_id is not None and bind_bridge_id == "":
                try:
                    result = m.edit_config(target="candidate", config=new_config_tree)
                    m.commit()

                except Exception as e:
                    print(f"Error: {e}")
                    return redirect("/vlans/create-vlan")

            if is_l2_vlan and bind_interface_name is not None:
                try:

small_web_app/routes/vlans.py
import xml.etree.ElementTree as ET

from flask import Blueprint, request, jsonify, redirect, render_template
from ncclient import manager

from constants import L3_VLAN_CREATION_STRING, L2_VLAN_CREATION_STRING, NAMESPACE

vlan_bp = Blueprint("vlans", __name__, url_prefix="/vlans")


@vlan_bp.route("/create-vlan", methods=["GET", "POST"])
def create_vlan():
    NEW_VLAN_CONFIG = None

    if request.method == "GET":
        return render_template("vlans.html")

    if request.method == "POST":

        bridge_id = request.form.get("bridge-id")
        bridge_protocol = request.form.get("bridge-protocol")
        vlan_id = request.form.get("vlan-id")
        vlan_state = request.form.get("vlan-state")
        vlan_layer = request.form.get("vlan-layer")

        VLAN_CONFIG = ET.fromstring(L3_VLAN_CREATION_STRING) if vlan_layer == "layer-3" else ET.fromstring(L2_VLAN_CREATION_STRING)

        bridge_id_tag = VLAN_CONFIG.find(".//ipi-network-instance:instance-name", namespaces=NAMESPACE)
        bridge_id_config_tag = VLAN_CONFIG.find(".//ipi-network-instance:config/ipi-network-instance:instance-name", namespaces=NAMESPACE)

        vlan_id_tag = VLAN_CONFIG.find(".//ipi-vlan:vlan/ipi-vlan:vlan-id", namespaces=NAMESPACE)
        vlan_config_id_tag = VLAN_CONFIG.find(".//ipi-vlan:vlan/ipi-vlan:config/ipi-vlan:vlan-id", namespaces=NAMESPACE)
        vlan_state_tag = VLAN_CONFIG.find(".//ipi-vlan:vlan/ipi-vlan:customer-vlan/ipi-vlan:config/ipi-vlan:state", namespaces=NAMESPACE)

        bridge_protocol_tag = VLAN_CONFIG.find(".//ipi-bridge:config/ipi-bridge:protocol", namespaces=NAMESPACE)

        if bridge_id_tag is not None: bridge_id_tag.text = bridge_id
        if bridge_id_config_tag is not None: bridge_id_config_tag.text = bridge_id

        if vlan_id_tag is not None: vlan_id_tag.text = vlan_id
        if vlan_config_id_tag is not None: vlan_config_id_tag.text = vlan_id
        if vlan_state_tag is not None: vlan_state_tag.text = "disable" if vlan_state == None else vlan_state

        if bridge_protocol_tag is not None: bridge_protocol_tag.text = bridge_protocol
        
        NEW_VLAN_CONFIG = ET.tostring(VLAN_CONFIG, encoding="unicode")

        with manager.connect(host="192.168.10.102", username="ocnos", password="ocnos", hostkey_verify=False) as m:
            try:
                vlan_result = m.edit_config(target="candidate", config=NEW_VLAN_CONFIG)
                m.commit()
            except Exception as e:
                print(f"Detailed error message: {e}")

        return redirect("/interfaces/")

small_web_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NETCONF Stuff</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">NETCONF Stuff</a>
        </div>
    </nav>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <main>
        {% block content %}{% endblock %}
    </main>
</body>

</html>

small_web_app/templates/configure_interface.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form action="{{ url_for('interfaces.configure_interface') }}" method="POST">
        <div class="mb-3">
            <label for="interfaceName" class="form-label">Interface Name</label>
            <input type="text" class="form-control" id="interfaceName" name="interface-name" value="{{ name or '' }}"
                readonly>
        </div>
        {% if ('eth' in name or 'vlan' in name) and isL2Vlan == False %}
        <div class="mb-3">
            <label for="interfaceIP" class="form-label">Primary IP Address</label>
            <input type="text" class="form-control" id="interfaceIP" name="interface-ip">
        </div>
        {% endif %}
        {% if 'vlan' in name %}
        <div class="mb-3">
            <label for="parentInterface" class="form-label">Interface to bind to</label>
            <input type="text" class="form-control" id="parentInterface" name="parent-interface">
            <br>
            <label for="switchportMode" class="form-label">Switchport Mode</label>
            <select name="switchport-mode" id="switchportMode" class="form-select">
                <option selected>Select Switchport Mode</option>
                <option value="access">access</option>
                <option value="hybrid">hybrid</option>
                <option value="trunk">trunk</option>
                <option value="provider-network">provider-network</option>
                <option value="customer-edge access">customer-edge access</option>
                <option value="customer-edge hybrid">customer-edge hybrid</option>
                <option value="customer-edge trunk">customer-edge trunk</option>
            </select>
            <input type="text" name="is-l2-vlan" value="{{ isL2Vlan }}" hidden>
        </div>
        {% endif %}
        {% if 'eth' in name %}
        <div class="mb-3">
            <label for="interfaceBridge" class="form-label">Bridge to bind to</label>
            <input type="text" class="form-control" id="interfaceBridge" name="bridge-interface">
        </div>
        <div class="mb-3">
            <input class="form-check-input" type="checkbox" id="interfaceIsSwitchport" name="is-switchport">
            <label class="form-check-label" for="interfaceIsSwitchport">
                Is Switchport
            </label>
        </div>
        {% endif %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

small_web_app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Instances</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Operational Status</th>
                <th scope="col">Admin Status</th>
            </tr>
        </thead>
        <tbody>
            {% for interface in data %}
            <tr>
                <th scope="row">{{ loop.index }}</th>
                <td> <a href="{{url_for('interfaces.configure_interface', name=interface.get('name'))}}">{{ interface.get("name")
                        }}</a> </td>
                <td>{{ interface.get("oper-status") }}</td>
                <td>{{ interface.get("admin-status") }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br />
    <h2>VLANS</h2>
    <p>Under Construction</p>
</div>

{% endblock %}

small_web_app/templates/interfaces.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Operational Status</th>
                <th scope="col">Admin Status</th>
            </tr>
        </thead>
        <tbody>
            {% for interface in data %}
            <tr>
                <th scope="row">{{ loop.index }}</th>
                <td> <a href="{{url_for('interfaces.configure_interface', name=interface.get('name'))}}">{{ interface.get("name")
                        }}</a> </td>
                <td>{{ interface.get("oper-status") }}</td>
                <td>{{ interface.get("admin-status") }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br /> 
    <a class="btn btn-primary" href="{{ url_for('vlans.create_vlan') }}" role="button">Create VLAN</a>
</div>

{% endblock %}

small_web_app/templates/vlans.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Create VLAN</h2>
    <form method="POST" action="{{ url_for('vlans.create_vlan') }}">
        <div class="mb-3">
            <label for="bridgeId" class="form-label">Bridge id &lpar;1-32&rpar;</label>
            <input class="form-control" id="bridgeId" name="bridge-id">
        </div>
        <div class="mb-3">
            <label for="bridgeProtocol" class="form-label">Bridge Protocol</label>
            <select name="bridge-protocol" id="bridgeProtocol" class="form-select">
                <option selected>Select Bridge Protocol</option>
                <option value="ieee">ieee</option>
                <option value="ieee-vlan-bridge">ieee vlan-bridge</option>
                <option value="rstp">rstp</option>
                <option value="rstp-vlan-bridge">rstp vlan-bridge</option>
                <option value="mstp">mstp</option>
                <option value="rstp-ring">rstp ring</option>
                <option value="mstp-ring">mstp ring</option>
                <option value="rstp-vlan-bridge-ring">rstp vlan-bridge ring</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="vlanId" class="form-label">VLAN ID &lpar;2-4094&rpar;</label>
            <input class="form-control" id="vlanId" name="vlan-id">
        </div>
        <div class="mb-3">
            <div class="form-check">
                <!-- checkbox value when unchecked-->
                <input name="vlan-state" value="disable" hidden id="hiddenInput">
                <input class="form-check-input" type="checkbox" value="enable" id="enableVLAN" name="vlan-state"
                    onchange="this.checked ? document.getElementById('hiddenInput').remove() : ''">
                <label class="form-check-label" for="enableVLAN">
                    Enable
                </label>
            </div>
        </div>
        <div class="mb-3 d-flex gap-3">
            <div class="form-check">
                <input class="form-check-input" type="radio" name="vlan-layer" id="layer2VLAN" value="layer-2" checked>
                <label class="form-check-label" for="layer2VLAN">
                    Layer 2 VLAN
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="vlan-layer" id="layer3VLAN" value="layer-3">
                <label class="form-check-label" for="layer3VLAN">
                    Layer 3 VLAN
                </label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}